language: go

sudo: required

os:
  - linux
  - osx

go:
  - tip

before_install:
  - go get -d github.com/libgit2/git2go
  - cd $GOPATH/src/github.com/libgit2/git2go
  - git checkout next
  - git submodule update --init
  - make install
  - cd $TRAVIS_BUILD_DIR
