language: go

sudo: required

go:
  - 1.6
  - tip

before_install:
  - go get -d github.com/libgit2/git2go
  - cd $GOPATH/src/github.com/libgit2/git2go
  - git checkout next
  - git submodule update --init
  - make install

script:
  - cd $GOPATH/src/git-time-metric/gtm
  - go get ./...
  - go install
  - go test -v ./...
