language: go

sudo: required

go:
  - 1.6

before_install:
  - go get -d github.com/libgit2/git2go
  - cd $GOPATH/src/github.com/libgit2/git2go
  - git checkout next
  - git submodule update --init
  - make install
