version: "{build}"

os: Visual Studio 2015

clone_folder: c:\gopath\src\github.com\git-time-metric\gtm

build_script:
  - c:\msys64\usr\bin\bash -lc /c/gopath/src/github.com/git-time-metric/gtm/script/appveyor-build.sh

artifacts:
  - path: gtm.$(appveyor_repo_tag).windows.tar.gz
    name: gtm.zip

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: O47of1Osqbk2qkk1Vn228XXF/YDwev5j5YHyNPzEPJR1pxuqwPaqlvsFDVUYQoiu
  artifact: gtm.zip
  force_update: true
  on:
    appveyor_repo_tag: true
