version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\git-time-metric\gtm

environment:
  GOPATH: c:\gopath

install:
  - go get -d github.com\libgit2\git2go
  - cd c:\gopath\src\github.com\libgit2\git2go
  - git checkout next
  - git submodule update --init
  - C:\MinGW\msys\1.0\bin\sh --login make install
  - cd -

build_script:
 - go get -t -v .\...
 - go test -v .\...
 - go install

