version: "{build}"

platform:
  - x64

clone_folder: c:\gopath\src\github.com\git-time-metric\gtm

environment:
  GOPATH: c:\gopath

install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - go get -d github.com\libgit2\git2go
  - cd c:\gopath\src\github.com\libgit2\git2go
  - git checkout next
  - git submodule update --init
  - bash  -lc "cp /c/gopath/src/github.com/git-time-metric/gtm/script/build-libgit2-static.sh /c/gopath/src/github.com/libgit2/git2go/script/build-libgit2-static.sh"
  - bash  -lc "pacman -S make mingw-w64-x86_64-cmake mingw-w64-x86_64-pkg-config git-core"
  - bash  -lc "cd /c/gopath/src/github.com/libgit2/git2go && make install"
  - cd c:\gopath\src\github.com\git-time-metric\gtm

build_script:
 - go get -t -v .\...
 - go test -v .\...
 - go install

