version: "{build}"

platform:
  - x64

clone_folder: c:\gopath\src\github.com\git-time-metric\gtm

environment:
  GOPATH: c:\gopath

install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  - go get -d github.com\libgit2\git2go
  - cd c:\gopath\src\github.com\libgit2\git2go
  - git checkout next
  - git submodule update --init
  - bash  -lc "make install"
  - cd -

build_script:
 - go get -t -v .\...
 - go test -v .\...
 - go install

